create table if not exists public.appointments (
    id bigint generated by default as identity primary key,
    user_email text,
    appointment_date date not null,
    appointment_time text not null,
    clinician_email text not null,
    appointment_type text not null check (appointment_type in ('in-person', 'video', 'phone')),
    location text not null,
    status text not null default 'upcoming' check (status in ('upcoming', 'completed', 'cancelled')),
    notes text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- insert into public.appointments (
--     user_email,
--     appointment_date,
--     appointment_time,
--     doctor,
--     specialty,
--     appointment_type,
--     location,
--     status,
--     notes
-- ) values
--     (null, '2026-04-05', '10:00 AM', 'Dr. Sarah Smith', 'Urologist', 'in-person', 'Medical Center - Room 302', 'upcoming', 'Follow-up consultation'),
--     (null, '2026-04-15', '2:30 PM', 'Dr. Michael Johnson', 'Oncologist', 'video', 'Virtual Appointment', 'upcoming', 'Risk assessment review'),
--     (null, '2026-03-01', '9:00 AM', 'Dr. Sarah Smith', 'Urologist', 'in-person', 'Medical Center - Room 302', 'completed', 'Annual PSA screening')
-- on conflict do nothing;