create table if not exists public.notifications (
    id bigint generated by default as identity primary key,
    recipient_email text not null,
    category text not null,
    title text not null,
    message text not null,
    appointment_id bigint,
    dedupe_key text unique,
    metadata jsonb not null default '{}'::jsonb,
    is_read boolean not null default false,
    created_at timestamptz not null default now(),
    read_at timestamptz
);

create index if not exists idx_notifications_recipient_created_at
    on public.notifications (recipient_email, created_at desc);

create index if not exists idx_notifications_unread
    on public.notifications (recipient_email, is_read);
